### ISSUE TITLE
Error: Class '\LolzInsuranceDeposit\Setup' not found in src/XF/AddOn/AddOn.php at line 455

### ISSUE THREAD

**Issue by Bugaga13** [I-ToSa-I/LolzInsuranceDeposit#1]
Hello.
I placed this addon to src/addons/
On installation there is error Error: Class '\LolzInsuranceDeposit\Setup' not found in src/XF/AddOn/AddOn.php at line 455
What can we do to install on XF 2.2.16 ?

**Comment by I-ToSa-I** [comment]
Hello. You have installed the addon incorrectly. This is how the structure should look like:

addon.zip/
- upload/
-- src/
--- addons/
---- DCS/
----- LolzInsuranceDeposit/
------ Setup.php
------ ...

And you have to install it through the admin panel. example.com/admin.php?add-ons/install-from-archive

Sorry for the long answer!
